name: ztd-matrix-20260927t050251795283z-0
services:
  sqlite:
    build:
      context: /var/folders/j2/k150yy6d74ld6gm3rk77rjkr0000gn/T/ztd-matrix-u0s3fr0r
      dockerfile: Dockerfile
      args:
        PHP_IMAGE: php:8.5-cli-bookworm
        PHP_VERSION: "8.5"
        SQLITE_SHA256: ""
        SQLITE_URL: ""
        SQLITE_VERSION: system
    command:
      - php
      - scripts/matrix-probe.php
    entrypoint: []
    environment:
      EXPECTED_DATABASE: "3"
      EXPECTED_PHP: "8.5"
      EXPECTED_SQLITE: system
      MATRIX_DATABASE: sqlite
      ZTD_VERSION_LOG: /evidence/versions.json
    image: ztd-scenario-matrix:20260927t050251795283z-php8.5-sqlitesystem
    networks:
      default: null
    volumes:
      - type: bind
        source: /Users/ab/Projects/ztd-query-php-scenario/cycles/2026/09/CYC-20260927T044631882598Z-docker-supported-matrix/negative-check/20260927T050251795283Z/php8.5-sqlitesystem
        target: /evidence
        bind: {}
networks:
  default:
    name: ztd-matrix-20260927t050251795283z-0_default
x-client:
  build:
    args:
      PHP_IMAGE: php:8.5-cli-bookworm
      PHP_VERSION: "8.5"
      SQLITE_SHA256: ""
      SQLITE_URL: ""
      SQLITE_VERSION: system
    context: /var/folders/j2/k150yy6d74ld6gm3rk77rjkr0000gn/T/ztd-matrix-u0s3fr0r
    dockerfile: Dockerfile
  command:
    - php
    - scripts/matrix-probe.php
  entrypoint: []
  environment:
    EXPECTED_DATABASE: "3"
    EXPECTED_PHP: "8.5"
    EXPECTED_SQLITE: system
    MATRIX_DATABASE: sqlite
    ZTD_VERSION_LOG: /evidence/versions.json
  image: ztd-scenario-matrix:20260927t050251795283z-php8.5-sqlitesystem
  volumes:
    - /Users/ab/Projects/ztd-query-php-scenario/cycles/2026/09/CYC-20260927T044631882598Z-docker-supported-matrix/negative-check/20260927T050251795283Z/php8.5-sqlitesystem:/evidence
