name: ztd-matrix-20260927t045248184172z-0
services:
  sqlite:
    build:
      context: /Users/ab/Projects/ztd-query-php-scenario
      dockerfile: Dockerfile
      args:
        PHP_IMAGE: php:8.1-cli-bookworm
        PHP_VERSION: "8.1"
        SQLITE_SHA256: 67d3fe6d268e6eaddcae3727fce58fcc8e9c53869bdd07a0c61e38ddf2965071
        SQLITE_URL: https://www.sqlite.org/2024/sqlite-autoconf-3460100.tar.gz
        SQLITE_VERSION: 3.46.1
    command:
      - php
      - scripts/matrix-probe.php
    entrypoint: []
    environment:
      EXPECTED_DATABASE: 3.46.1
      EXPECTED_PHP: "8.1"
      EXPECTED_SQLITE: 3.46.1
      MATRIX_DATABASE: sqlite
      ZTD_VERSION_LOG: /evidence/versions.json
    image: ztd-scenario-matrix:php8.1-sqlite3.46.1
    networks:
      default: null
    volumes:
      - type: bind
        source: /Users/ab/Projects/ztd-query-php-scenario/cycles/2026/09/CYC-20260927T044631882598Z-docker-supported-matrix/environment/20260927T045248184172Z/php8.1-sqlite3.46.1
        target: /evidence
        bind: {}
networks:
  default:
    name: ztd-matrix-20260927t045248184172z-0_default
x-client:
  build:
    args:
      PHP_IMAGE: php:8.1-cli-bookworm
      PHP_VERSION: "8.1"
      SQLITE_SHA256: 67d3fe6d268e6eaddcae3727fce58fcc8e9c53869bdd07a0c61e38ddf2965071
      SQLITE_URL: https://www.sqlite.org/2024/sqlite-autoconf-3460100.tar.gz
      SQLITE_VERSION: 3.46.1
    context: ..
    dockerfile: Dockerfile
  command:
    - php
    - scripts/matrix-probe.php
  entrypoint: []
  environment:
    EXPECTED_DATABASE: 3.46.1
    EXPECTED_PHP: "8.1"
    EXPECTED_SQLITE: 3.46.1
    MATRIX_DATABASE: sqlite
    ZTD_VERSION_LOG: /evidence/versions.json
  image: ztd-scenario-matrix:php8.1-sqlite3.46.1
  volumes:
    - /Users/ab/Projects/ztd-query-php-scenario/cycles/2026/09/CYC-20260927T044631882598Z-docker-supported-matrix/environment/20260927T045248184172Z/php8.1-sqlite3.46.1:/evidence
