<?php

declare(strict_types=1);

namespace Tests\Pdo;

use Tests\Support\AbstractMysqlPdoTestCase;

/**
 * Tests MySQL UPDATE ... JOIN with inline data patterns.
 *
 * MySQL does not support UPDATE FROM VALUES directly, but achieves similar
 * results through UPDATE ... JOIN subquery patterns. These are commonly
 * generated by ORMs and application code for batch updates.
 *
 * @spec SPEC-4.2
 */
class MysqlUpdateJoinValuesTest extends AbstractMysqlPdoTestCase
{
    protected function getTableDDL(): string|array
    {
        return [
            "CREATE TABLE my_ujv_products (
                id INT PRIMARY KEY,
                name VARCHAR(100) NOT NULL,
                price DECIMAL(10,2) NOT NULL,
                stock INT NOT NULL DEFAULT 0
            )",
        ];
    }

    protected function getTableNames(): array
    {
        return ['my_ujv_products'];
    }

    protected function setUp(): void
    {
        parent::setUp();

        $this->pdo->exec("INSERT INTO my_ujv_products (id, name, price, stock) VALUES (1, 'Widget', 10.00, 100)");
        $this->pdo->exec("INSERT INTO my_ujv_products (id, name, price, stock) VALUES (2, 'Gadget', 20.00, 50)");
        $this->pdo->exec("INSERT INTO my_ujv_products (id, name, price, stock) VALUES (3, 'Doohickey', 30.00, 25)");
        $this->pdo->exec("INSERT INTO my_ujv_products (id, name, price, stock) VALUES (4, 'Thingamajig', 40.00, 10)");
    }

    /**
     * UPDATE JOIN with UNION ALL subquery (MySQL batch update pattern).
     *
     * This is the MySQL equivalent of PostgreSQL's UPDATE FROM VALUES.
     */
    public function testUpdateJoinUnionAll(): void
    {
        try {
            $this->pdo->exec("
                UPDATE my_ujv_products AS p
                INNER JOIN (
                    SELECT 1 AS id, 15.00 AS new_price
                    UNION ALL SELECT 3, 35.00
                ) AS v ON p.id = v.id
                SET p.price = v.new_price
            ");

            $rows = $this->ztdQuery("SELECT id, price FROM my_ujv_products ORDER BY id");

            $this->assertCount(4, $rows);

            if (abs((float) $rows[0]['price'] - 15.00) > 0.01) {
                $this->markTestIncomplete(
                    'UPDATE JOIN UNION: id=1 price=' . $rows[0]['price']
                    . ', expected 15.00. UPDATE JOIN may not work in shadow.'
                );
            }

            $this->assertEquals(15.00, (float) $rows[0]['price'], '', 0.01);
            $this->assertEquals(20.00, (float) $rows[1]['price'], '', 0.01); // unchanged
            $this->assertEquals(35.00, (float) $rows[2]['price'], '', 0.01);
            $this->assertEquals(40.00, (float) $rows[3]['price'], '', 0.01); // unchanged
        } catch (\Throwable $e) {
            $this->markTestIncomplete('UPDATE JOIN UNION ALL failed: ' . $e->getMessage());
        }
    }

    /**
     * UPDATE JOIN with multiple SET columns.
     */
    public function testUpdateJoinMultipleColumns(): void
    {
        try {
            $this->pdo->exec("
                UPDATE my_ujv_products AS p
                INNER JOIN (
                    SELECT 1 AS id, 12.50 AS new_price, 200 AS new_stock
                    UNION ALL SELECT 2, 22.50, 75
                    UNION ALL SELECT 4, 45.00, 5
                ) AS v ON p.id = v.id
                SET p.price = v.new_price, p.stock = v.new_stock
            ");

            $rows = $this->ztdQuery("SELECT id, price, stock FROM my_ujv_products ORDER BY id");

            $this->assertCount(4, $rows);
            $this->assertEquals(12.50, (float) $rows[0]['price'], '', 0.01);
            $this->assertSame(200, (int) $rows[0]['stock']);
            $this->assertEquals(22.50, (float) $rows[1]['price'], '', 0.01);
            $this->assertSame(75, (int) $rows[1]['stock']);
            $this->assertEquals(30.00, (float) $rows[2]['price'], '', 0.01); // unchanged
            $this->assertEquals(45.00, (float) $rows[3]['price'], '', 0.01);
            $this->assertSame(5, (int) $rows[3]['stock']);
        } catch (\Throwable $e) {
            $this->markTestIncomplete('UPDATE JOIN multiple columns failed: ' . $e->getMessage());
        }
    }

    /**
     * Prepared UPDATE JOIN with ? parameters.
     */
    public function testPreparedUpdateJoin(): void
    {
        try {
            $stmt = $this->pdo->prepare("
                UPDATE my_ujv_products AS p
                INNER JOIN (
                    SELECT ? AS id, ? AS new_price
                ) AS v ON p.id = v.id
                SET p.price = v.new_price
            ");
            $stmt->execute([1, 99.99]);

            $rows = $this->ztdQuery("SELECT id, price FROM my_ujv_products WHERE id = 1");

            if (abs((float) $rows[0]['price'] - 99.99) > 0.01) {
                $this->markTestIncomplete(
                    'Prepared UPDATE JOIN: price=' . $rows[0]['price']
                    . ', expected 99.99. Prepared params in JOIN subquery may not work.'
                );
            }

            $this->assertEquals(99.99, (float) $rows[0]['price'], '', 0.01);
        } catch (\Throwable $e) {
            $this->markTestIncomplete('Prepared UPDATE JOIN failed: ' . $e->getMessage());
        }
    }

    /**
     * UPDATE JOIN with expression in SET (accumulate pattern).
     */
    public function testUpdateJoinAccumulate(): void
    {
        try {
            $this->pdo->exec("
                UPDATE my_ujv_products AS p
                INNER JOIN (
                    SELECT 1 AS id, 50 AS add_stock
                    UNION ALL SELECT 2, 100
                ) AS v ON p.id = v.id
                SET p.stock = p.stock + v.add_stock
            ");

            $rows = $this->ztdQuery("SELECT id, stock FROM my_ujv_products ORDER BY id");

            $this->assertSame(150, (int) $rows[0]['stock']); // 100 + 50
            $this->assertSame(150, (int) $rows[1]['stock']); // 50 + 100
            $this->assertSame(25, (int) $rows[2]['stock']);   // unchanged
        } catch (\Throwable $e) {
            $this->markTestIncomplete('UPDATE JOIN accumulate failed: ' . $e->getMessage());
        }
    }

    /**
     * UPDATE JOIN after prior shadow INSERT.
     */
    public function testUpdateJoinAfterInsert(): void
    {
        try {
            $this->pdo->exec("INSERT INTO my_ujv_products (id, name, price, stock) VALUES (5, 'Gizmo', 50.00, 0)");

            $this->pdo->exec("
                UPDATE my_ujv_products AS p
                INNER JOIN (
                    SELECT 5 AS id, 30 AS new_stock
                ) AS v ON p.id = v.id
                SET p.stock = v.new_stock
            ");

            $rows = $this->ztdQuery("SELECT id, stock FROM my_ujv_products WHERE id = 5");

            if (count($rows) !== 1) {
                $this->markTestIncomplete(
                    'UPDATE JOIN after INSERT: id=5 not found.'
                );
            }

            if ((int) $rows[0]['stock'] !== 30) {
                $this->markTestIncomplete(
                    'UPDATE JOIN after INSERT: id=5 stock=' . $rows[0]['stock']
                    . ', expected 30. Shadow-inserted rows may not be visible to UPDATE JOIN.'
                );
            }

            $this->assertSame(30, (int) $rows[0]['stock']);
        } catch (\Throwable $e) {
            $this->markTestIncomplete('UPDATE JOIN after INSERT failed: ' . $e->getMessage());
        }
    }

    /**
     * DELETE JOIN with inline data (batch delete by id list pattern).
     */
    public function testDeleteJoinInlineIds(): void
    {
        try {
            $this->pdo->exec("
                DELETE p FROM my_ujv_products AS p
                INNER JOIN (
                    SELECT 2 AS id
                    UNION ALL SELECT 4
                ) AS v ON p.id = v.id
            ");

            $rows = $this->ztdQuery("SELECT id FROM my_ujv_products ORDER BY id");

            if (count($rows) !== 2) {
                $this->markTestIncomplete(
                    'DELETE JOIN: expected 2 remaining rows (1,3), got ' . count($rows)
                    . '. Ids: ' . json_encode(array_column($rows, 'id'))
                );
            }

            $this->assertCount(2, $rows);
            $this->assertSame(1, (int) $rows[0]['id']);
            $this->assertSame(3, (int) $rows[1]['id']);
        } catch (\Throwable $e) {
            $this->markTestIncomplete('DELETE JOIN inline ids failed: ' . $e->getMessage());
        }
    }
}
